### ISSUE TITLE
iPXE boot menu broken RC-9

### ISSUE THREAD

**Issue by Nightreaver** [FOGProject/fogproject#123]
Hello

I've updated to RC-9 today and hit the following issue when entering the iPXE menu, after you type username/password from 'hidden' login

```
PHP Warning:  array_map(): An error occurred while invoking the map callback in /var/www/html/fog/lib/fog/bootmenu.class.php on line 1053
PHP Fatal error:  Uncaught exception 'Exception' with message 'Key must be a string or index' in /var/www/html/fog/lib/fog/fogbase.class.php:720\nStack trace:\n
#0 /var/www/html/fog/lib/fog/bootmenu.class.php(952): FOGBase->arrayInsertAfter(1, Array, 'extra', 'param extraargs...')\n
#1 /var/www/html/fog/lib/fog/bootmenu.class.php(1051): BootMenu->menuOpt(Object(PXEMenuOptions), 'mode=onlydebug')\n
#2 [internal function]: BootMenu->{closure}(Object(PXEMenuOptions))\n
#3 /var/www/html/fog/lib/fog/bootmenu.class.php(1053): array_map(Object(Closure), Array)\n
#4 /var/www/html/fog/lib/fog/bootmenu.class.php(208): BootMenu->printDefault()\n
#5 [internal function]: BootMenu->__construct(Object(Host))\n
#6 /var/www/html/fog/lib/fog/fogbase.class.php(376): ReflectionClass->newInstance(Object(Host))\n
#7 /var/www/html/fog/service/ipxe/boot.php(36): FOGBase::getClass('BootMenu', Object(Host))\n
#8 {main}\n  thrown in /var/www/html/fog/lib/fog/fogbase.class.php on line 720
```

seem to look different on a registered host

```
PHP Warning:  array_map(): An error occurred while invoking the map callback in /var/www/html/fog/lib/fog/bootmenu.class.php on line 1053
[Mon Sep 05 17:37:57.280597 2016] [:error] [pid 951] [client 192.168.106.188:7233] PHP Fatal error:  Uncaught exception 'Exception' with message 'Key must be a string or index' in /var/www/html/fog/lib/fog/fogbase.class.php:720\nStack trace:\n
#0 /var/www/html/fog/lib/fog/bootmenu.class.php(952): FOGBase->arrayInsertAfter(1, Array, 'extra', 'param extraargs...')\n
#1 /var/www/html/fog/lib/fog/bootmenu.class.php(1051): BootMenu->menuOpt(Object(PXEMenuOptions), 'mode=onlydebug')\n
#2 [internal function]: BootMenu->{closure}(Object(PXEMenuOptions))\n
#3 /var/www/html/fog/lib/fog/bootmenu.class.php(1053): array_map(Object(Closure), Array)\n
#4 /var/www/html/fog/lib/fog/bootmenu.class.php(762): BootMenu->printDefault()\n
#5 /var/www/html/fog/lib/fog/bootmenu.class.php(210): BootMenu->getTasking()\n
#6 [internal function]: BootMenu->__construct(Object(Host))\n
#7 /var/www/html/fog/lib/fog/fogbase.class.php(376): ReflectionClass->newInstance(Object(Host))\n
#8 /var/www/html/fog/service/ipxe/boot.php(36): FOGBase::getClass('BootMenu', Object(Host))\n
#9 {main}\n  thrown in /var/www/html/fog/lib/fog/fogbase.class.php on line 720
```  

Then it fails with chainloading error.

Regards

**Comment by mastacontrola** [comment]
Already reported and fixed for RC-10.

Sorry I missed it.

**Comment by Nightreaver** [comment]
Any quick fix for now?

**Comment by mastacontrola** [comment]
Yep, one sec:
Open /var/www/html/fog/lib/fog/fogbase.class.php

At line 719 change it from:

`if (!is_string($key)) {`

To:
`if (!is_string($key) && !is_numeric($key)) {`

**Comment by Nightreaver** [comment]
Thanks!
