### ISSUE TITLE
[1.5.10] Can't "Create New Image"

### ISSUE THREAD

**Issue by TanguyPSV** [FOGProject/fogproject#578]
**Describe the bug**
I recently upgrade both my OS (Debian 10 -> 11 --> 12) and FOG (1.5.9 => 1.5.10). At each step I tested "Deploy" and "Capture" task but forgot to test "Image creation". Now, if I click on "Create New Image", it give a blank screen.

**To Reproduce**
1. Go to "Images"
2. Click on "Create New Image"

**Expected behavior**
The image creation page to display.

**Software (please complete the following information):**
 - FOG version 1.5.10
 - FOS kernel 6.1.0-13-amd64
 - OS: Debian 12

**Additional context**
Apache2 log when I click on "Create New Image"

AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught ValueError: min(): Argument #1 ($value) must contain at least one element in /var/www/fog/lib/fog/storagegroup.class.php:228\nStack trace:\n#0 /var/www/fog/lib/fog/storagegroup.class.php(228): min()\n#1 /var/www/fog/lib/pages/imagemanagementpage.class.php(481): StorageGroup->getMasterStorageNode()\n#2 /var/www/fog/lib/fog/fogpagemanager.class.php(220): ImageManagementPage->add()\n#3 /var/www/fog/management/index.php(58): FOGPageManager->render()\n#4 {main}\n  thrown in /var/www/fog/lib/fog/storagegroup.class.php on line 228', referer: http://172.29.10.9/fog/management/index.php?node=image&sub=list

All other menu worked. I can list all my current image with "List All Images"

**Comment by darksidemilk** [comment]
Sorry for the delayed response to your issue here. 

4 questions

* Are you still having this issue?
* Have you tried updating to the latest stable release?
* What version of PHP are you using? `php -v`
* Can you confirm your storage node and storage group settings are correct and working? i.e the IP is set to the IP or hostname that your server can resolve to a storage node and each storage node belongs to a storage group.

**Comment by darksidemilk** [comment]
Closing due to inactivity. I'm also pretty sure this is fixed in the latest versions. If you're still having the issue, feel free to reply and we can reopen the issue @TanguyPSV

**Comment by TanguyPSV** [comment]
Hi, I just upgrade to the latest stable, and I still have the same issue.

"Can you confirm your storage node and storage group settings are correct and working? i.e the IP is set to the IP or hostname that your server can resolve to a storage node and each storage node belongs to a storage group."

How/where can I check that?

**Comment by TanguyPSV** [comment]
`php -v
PHP 8.2.26 (cli) (built: Nov 25 2024 17:21:51) (NTS)
`
