### ISSUE TITLE
Question: LDAP setup with Authentik

### ISSUE THREAD

**Issue by mpweya** [FOGProject/fogproject#669]
Hi!

I'm trying to setup the LDAP plugin with the authentik ldap provider. Sadly, I'm failing to configure it correctly. Could you help me find all the correct config values?

Let's assume the fog server can reach the authentik host via an unencrypted connection. Futhermore assume the following setup:
- fog search user: fogservice
- group for all fog admins: fogadmins
- group for all fog users: fogusers
- authentik host: authentik.mydomain.com
- basedn configured in authentik: OU=fog,DC=mydomain,DC=com

The furthest I got is with username attribute "cn" and group membership attribute "memberOf" which results in a logged error when I try to login with the user fogadmin

```
 Got error 'PHP message: Plugin LDAP::_result(). Search Method: search; Filter: (&(|(name=fogadmin))(memberof=cn=fogadmin,ou=users,ou=fog,dc=mydomain,dc=com,)); Result: 0PHP message: PHP Warning:  ldap_search(): Search: Operations error in /var/www/html/fog/lib/plugins/ldap/class/ldap.class.php on line 124PHP message: PHP Fatal error:  Uncaught TypeError: ldap_count_entries(): Argument #2 ($result) must be of type LDAP\\Result, bool given in /var/www/html/fog/lib/plugins/ldap/class/ldap.class.php:124\nStack trace:\n#0 /var/www/html/fog/lib/plugins/ldap/class/ldap.class.php(124): ldap_count_entries()\n#1 /var/www/html/fog/lib/plugins/ldap/class/ldap.class.php(843): LDAP->__call()\n#2 /var/www/html/fog/lib/plugins/ldap/class/ldap.class.php(663): LDAP->_result()\n#3 /var/www/html/fog/lib/plugins/ldap/class/ldap.class.php(559): LDAP->_getAccessLevel()\n#4 /var/www/html/fog/lib/plugins/ldap/hooks/ldappluginhook.hook.php(126): LDAP->authLDAP()\n#5 /var/www/html/fog/lib/fog/hookmanager.class.php(86): LDAPPluginHook->checkAddUser()\n#6 /var/www/html/fog/lib/fog/user.class.php(144): HookManager->processEvent()\n#7 /var/www/html/fog/lib/fog/user.class.php(226): User->passwordValidate()\n#8 /var/www/html/fog/lib/fog/fogbase.class.php(2469): User->validatePw()\n#9 /var/www/html/fog/lib/pages/processlogin.class.php(153): F...', referer: http://10.10.0.12/fog/management/index.php?node=home
```

**Comment by darksidemilk** [comment]
Firstly, what version of FOG are you running?

Second I would start with a simpler configuration like a search base of just "DC=mydomain,DC=com" and then make it more fine grained after that root base is working.

**Comment by mpweya** [comment]
The server is currently running 1.5.10.41.

The search base is freely configurable. It has to be unique as written in the docs https://docs.goauthentik.io/docs/add-secure-apps/providers/ldap/
So this is kind of the simplest setup I could configure.

**Comment by darksidemilk** [comment]
@McCrafterIV Sorry for the delay, back from the holidays now.
I would suggest updating at least to the latest stable branch, I believe there have been some bug fixes for the ldap plugin since the version you're on.
Can you screenshot your current ldap config screen in fog and share that? Seems like it doesn't like the way the user to login and do the ldap searching is the issue.

**Comment by mastacontrola** [comment]
I'm seeing a problem on your memberof query:
```memberof=cn=fogadmin,ou=users,ou=fog,dc=mydomain,dc=com,```

See the trailing comma? That, I think, is potentially breaking your ldap query.

**Comment by mpweya** [comment]
Sadly I'm unable to continue to investigate the problem at the moment. I'll close the issue for now and reopen it once I am able to test your suggestions and provide further information. Thanks so far!
